version: '3.8'
services:
  apache:
    container_name: php-apache
    image: php:8.0-apache
    volumes:
      - .:/var/www/html/
    ports: 
      - 8080:8080
  #python:
    #container_name: python
    #image: python:3.8
    #volumes:
     # - .:/python.py
    #ports:
     # - 5000:5000

