
name: Experiment

on: [workflow_dispatch]

jobs:

  test:
    runs-on: ubuntu-latest

    steps: 
    - name: Check out code
      uses: actions/checkout@v3

    - name: docker
      run: echo docker-compose up #--abort-on-container-exit

    - name: print
      run: echo "All done!"

