#--abort-on-container-exit
name: Experiment


on: [push, workflow_dispatch]

jobs:

  test:
    runs-on: ubuntu-latest

    steps: 
    - name: Check out code
      uses: actions/checkout@v3

    - name: docker
      run: docker-compose up
    
    - name: conf
      run: docker ps -a

    - name: print
      run: echo "All done!"

